import {
  CaretDownOutlined as DownIcon,
  LeftOutlined as ArrowBackIcon,
  SettingFilled as SettingsIcon,
  PlusOutlined as PlusIcon,
  CloseOutlined as CrossIcon,
  EllipsisOutlined as ThreeDotsIcon,
  SearchOutlined as SearchIcon,
  AppstoreFilled as FourSquaresIcon,
  MenuOutlined as ThreeLinsStackIcon,
  EditOutlined as PenIcon,
  TeamOutlined as PeopleIcon,
  DeleteFilled as DeleteIcon,
  FolderOpenOutlined as OpenFolderIcon,
  SaveOutlined as SaveIcon,
  CommentOutlined as CommentIcon,
} from "@ant-design/icons";

export {
  DownIcon,
  ArrowBackIcon,
  SettingsIcon,
  PlusIcon,
  CrossIcon,
  ThreeDotsIcon,
  SearchIcon,
  FourSquaresIcon,
  ThreeLinsStackIcon,
  PenIcon,
  PeopleIcon,
  DeleteIcon,
  OpenFolderIcon,
  SaveIcon,
  CommentIcon,
};
